--------------------------------------------------------
--  Fichier cr�� - jeudi-juin-04-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SEWER
--------------------------------------------------------

  CREATE TABLE "ZIGOOCARE"."SEWER" 
   (	"SEWER_ID" NUMBER, 
	"LOCATION" VARCHAR2(200 BYTE), 
	"MAX_CAPACITY" NUMBER, 
	"CURRENT_CAPACITY" NUMBER, 
	"WATER_LEVEL" NUMBER, 
	"BLOCKAGE_RATE" NUMBER, 
	"MUNICIPALITY_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MUNICIPALITY
--------------------------------------------------------

  CREATE TABLE "ZIGOOCARE"."MUNICIPALITY" 
   (	"MUNICIPALITY_ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"REGION" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"LONGITUDE" VARCHAR2(50 BYTE), 
	"LATITUDE" VARCHAR2(50 BYTE), 
	"RADIUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECYCLING_CENTER
--------------------------------------------------------

  CREATE TABLE "ZIGOOCARE"."RECYCLING_CENTER" 
   (	"CENTER_ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"MAX_CAPACITY" NUMBER, 
	"CURRENT_CAPACITY" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE), 
	"MUNICIPALITY_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INTERVENES
--------------------------------------------------------

  CREATE TABLE "ZIGOOCARE"."INTERVENES" 
   (	"TEAM_ID" NUMBER, 
	"SEWER_ID" NUMBER, 
	"INTERVENTION_DATE" DATE, 
	"PRIORITY" NUMBER, 
	"STATUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "ZIGOOCARE"."EMPLOYEE" 
   (	"EMPLOYEE_ID" NUMBER, 
	"NIC" VARCHAR2(8 BYTE), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"POSITION" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(64 BYTE), 
	"QUESTION" VARCHAR2(200 BYTE), 
	"ANSWER" VARCHAR2(64 BYTE), 
	"FINGERPRINT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COLLECTION_TEAM
--------------------------------------------------------

  CREATE TABLE "ZIGOOCARE"."COLLECTION_TEAM" 
   (	"TEAM_ID" NUMBER, 
	"TEAM_SIZE" NUMBER, 
	"VEHICLE_PLATE" VARCHAR2(20 BYTE), 
	"CONTACT_NUMBER" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER, 
	"AVERAGE_RATING" NUMBER, 
	"RATING_COUNT" NUMBER, 
	"ACTIVE_ASSIGNMENT" NUMBER, 
	"AVERAGE_COMPLETION_TIME" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ZIGOOCARE.SEWER
SET DEFINE OFF;
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (4,'35.821430,10.634422',100,0,20,23,5);
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (5,'35.858900,10.593900',100,0,30,2,5);
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (6,'35.871200,10.571200',100,0,20,30,5);
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (7,'35.729200,10.580800',100,0,56,23,5);
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (8,'35.956100,10.472200',100,0,85,15,5);
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (188,'37.288132,9.857330',20,6,10,30,4);
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (189,'35.681561,10.099511',100,30,20,30,2);
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (190,'36.729654,9.180307',100,50,20,50,null);
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (192,'35.678672,10.076803',20,2,10,10,2);
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (193,'35.660682,10.088820',50,12,6,24,2);
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (2,'36.850000,10.033300',100,0,0,0,1);
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (3,'36.949200,10.170600',100,0,0,0,1);
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (194,'34.751776,10.747514',30,9,4,30,3);
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (1,'36.862500,10.195600',100,100,15,100,1);
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (195,'34.760803,10.762620',60,16,7,26,3);
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (196,'37.278825,9.861626',30,15,5,50,4);
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (197,'37.272910,9.860306',20,2,6,10,4);
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (198,'36.726015,9.183049',30,23,4,76,null);
Insert into ZIGOOCARE.SEWER (SEWER_ID,LOCATION,MAX_CAPACITY,CURRENT_CAPACITY,WATER_LEVEL,BLOCKAGE_RATE,MUNICIPALITY_ID) values (199,'36.725717,9.183315',20,10,4,50,null);
REM INSERTING into ZIGOOCARE.MUNICIPALITY
SET DEFINE OFF;
Insert into ZIGOOCARE.MUNICIPALITY (MUNICIPALITY_ID,NAME,REGION,ADDRESS,PHONE,EMAIL,LONGITUDE,LATITUDE,RADIUS) values (1,'Ariana','Ariana','Palais de la municipalite, Avenue du 18 Janvier 1952, 2080 Ariana, Tunisie','+216 71 711 100','webmaster@commune-ariana.gov.tn','10.1893158','36.8579558',3000);
Insert into ZIGOOCARE.MUNICIPALITY (MUNICIPALITY_ID,NAME,REGION,ADDRESS,PHONE,EMAIL,LONGITUDE,LATITUDE,RADIUS) values (2,'Kairouan','Kairouan','Avenue de la R�publique, 3100 Kairouan, Tunisie','+216 77 227 300','commune.kairouan@planet.tn','10.0963','35.6781',8000);
Insert into ZIGOOCARE.MUNICIPALITY (MUNICIPALITY_ID,NAME,REGION,ADDRESS,PHONE,EMAIL,LONGITUDE,LATITUDE,RADIUS) values (3,'Sfax','Sfax','Avenue Habib Bourguiba, Sfax','+216 74 296 666','commune.sfax@topnet.tn','10.7603','34.7406',2500);
Insert into ZIGOOCARE.MUNICIPALITY (MUNICIPALITY_ID,NAME,REGION,ADDRESS,PHONE,EMAIL,LONGITUDE,LATITUDE,RADIUS) values (4,'Bizerte','Bizerte','Avenue Habib Bourguiba, 7000 Bizerte, Tunisie','+216 72 422 000','commune.bizerte@planet.tn','9.8739','37.2744',10000);
Insert into ZIGOOCARE.MUNICIPALITY (MUNICIPALITY_ID,NAME,REGION,ADDRESS,PHONE,EMAIL,LONGITUDE,LATITUDE,RADIUS) values (5,'Sousse','Sousse','Place de la Municipalit�, 4000 Sousse, Tunisie','+216 73 225 411','commune.sousse@topnet.tn','10.6360','35.8256',10000);
Insert into ZIGOOCARE.MUNICIPALITY (MUNICIPALITY_ID,NAME,REGION,ADDRESS,PHONE,EMAIL,LONGITUDE,LATITUDE,RADIUS) values (6,'Gabes','Gab�s','Centre Ville, Gabes','+216 75 274 000','commune.gabes@topnet.tn','10.0982','33.8815',2800);
Insert into ZIGOOCARE.MUNICIPALITY (MUNICIPALITY_ID,NAME,REGION,ADDRESS,PHONE,EMAIL,LONGITUDE,LATITUDE,RADIUS) values (7,'Aousja','Bizerte','Municipalit� d�Aousja, Tunisie','12345678','aousja@gmail.com','9.58','37.06',8000);
Insert into ZIGOOCARE.MUNICIPALITY (MUNICIPALITY_ID,NAME,REGION,ADDRESS,PHONE,EMAIL,LONGITUDE,LATITUDE,RADIUS) values (8,'Ghar El Melh','Bizerte','Municipalit� de Ghar El Melh, Tunisie','90006520','gharilmeleh@gmail.com','9.70','37.18',8000);
Insert into ZIGOOCARE.MUNICIPALITY (MUNICIPALITY_ID,NAME,REGION,ADDRESS,PHONE,EMAIL,LONGITUDE,LATITUDE,RADIUS) values (9,'Le Kef','Le Kef','Centre Ville, Le Kef','+216 78 228 222','commune.kef@topnet.tn','8.7049','36.1742',2000);
Insert into ZIGOOCARE.MUNICIPALITY (MUNICIPALITY_ID,NAME,REGION,ADDRESS,PHONE,EMAIL,LONGITUDE,LATITUDE,RADIUS) values (11,'Siliana','Siliana','Avenue de la R�publique, Siliana','+216 78 871 222','commune.siliana@planet.tn','9.3667','36.0833',2300);
REM INSERTING into ZIGOOCARE.RECYCLING_CENTER
SET DEFINE OFF;
Insert into ZIGOOCARE.RECYCLING_CENTER (CENTER_ID,NAME,ADDRESS,EMAIL,MAX_CAPACITY,CURRENT_CAPACITY,STATUS,MUNICIPALITY_ID) values (1,'Center Ariana','Pole Technologique, Cite El Ghazela','maquette@zigoocare.tn',200,90,'Active',1);
Insert into ZIGOOCARE.RECYCLING_CENTER (CENTER_ID,NAME,ADDRESS,EMAIL,MAX_CAPACITY,CURRENT_CAPACITY,STATUS,MUNICIPALITY_ID) values (2,'ANGed','6 Rue Al amine Al Abbassi 100 le belvedere tunis','azizmehrez@zigoocare.com',10,6,'Active',3);
Insert into ZIGOOCARE.RECYCLING_CENTER (CENTER_ID,NAME,ADDRESS,EMAIL,MAX_CAPACITY,CURRENT_CAPACITY,STATUS,MUNICIPALITY_ID) values (3,'Eco Group Tunisie','ZI Thyna 1, Sfax','hammamimaissa04@zigoocare.com',100,50,'Saturated',3);
Insert into ZIGOOCARE.RECYCLING_CENTER (CENTER_ID,NAME,ADDRESS,EMAIL,MAX_CAPACITY,CURRENT_CAPACITY,STATUS,MUNICIPALITY_ID) values (4,'TD Recycling','Zone industrielle 20 Mars, Sejoumi, Tunis','youssef.bouchehioua@zigoocare.tn',100,48,'Active',null);
Insert into ZIGOOCARE.RECYCLING_CENTER (CENTER_ID,NAME,ADDRESS,EMAIL,MAX_CAPACITY,CURRENT_CAPACITY,STATUS,MUNICIPALITY_ID) values (5,'Carthage Marine','CarthageAmilcar av.Mohamed Ali , Tunis','medazizdarnaoui@zigoocare.com',200,21,'Saturated',4);
Insert into ZIGOOCARE.RECYCLING_CENTER (CENTER_ID,NAME,ADDRESS,EMAIL,MAX_CAPACITY,CURRENT_CAPACITY,STATUS,MUNICIPALITY_ID) values (6,'SOREAL','Zone industrielle Enfidha, Sousse','bouchehiouay@zigoocare.com',200,193,'Active',5);
Insert into ZIGOOCARE.RECYCLING_CENTER (CENTER_ID,NAME,ADDRESS,EMAIL,MAX_CAPACITY,CURRENT_CAPACITY,STATUS,MUNICIPALITY_ID) values (7,'ELEC RECYCLAGE','ZI Utique Lot N50 - 7060 Bizerte','hammami.maissa@zigoocare.tn',620,200,'Active',4);
REM INSERTING into ZIGOOCARE.INTERVENES
SET DEFINE OFF;
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (3,5,to_date('06-05-26','DD-MM-RR'),3,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (3,4,to_date('06-05-26','DD-MM-RR'),4,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (3,7,to_date('06-05-26','DD-MM-RR'),5,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (3,5,to_date('07-05-26','DD-MM-RR'),3,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (4,189,to_date('02-05-26','DD-MM-RR'),1,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (4,190,to_date('02-05-26','DD-MM-RR'),1,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (4,198,to_date('02-05-26','DD-MM-RR'),2,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (3,8,to_date('02-05-26','DD-MM-RR'),1,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (3,6,to_date('02-05-26','DD-MM-RR'),2,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (4,199,to_date('02-05-26','DD-MM-RR'),3,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (3,8,to_date('07-05-26','DD-MM-RR'),1,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (3,197,to_date('02-05-26','DD-MM-RR'),2,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (3,196,to_date('02-05-26','DD-MM-RR'),3,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (3,188,to_date('02-05-26','DD-MM-RR'),4,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (5,2,to_date('02-05-26','DD-MM-RR'),1,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (5,1,to_date('02-05-26','DD-MM-RR'),2,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (5,3,to_date('02-05-26','DD-MM-RR'),3,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (3,6,to_date('07-05-26','DD-MM-RR'),2,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (3,4,to_date('07-05-26','DD-MM-RR'),4,1);
Insert into ZIGOOCARE.INTERVENES (TEAM_ID,SEWER_ID,INTERVENTION_DATE,PRIORITY,STATUS) values (3,7,to_date('07-05-26','DD-MM-RR'),5,1);
REM INSERTING into ZIGOOCARE.EMPLOYEE
SET DEFINE OFF;
Insert into ZIGOOCARE.EMPLOYEE (EMPLOYEE_ID,NIC,FIRST_NAME,LAST_NAME,POSITION,EMAIL,PASSWORD,QUESTION,ANSWER,FINGERPRINT) values (1,'12345678','Mohamed El Aziz','Mehrez','Human Resources','azizm@email.tn',null,null,null,null);
Insert into ZIGOOCARE.EMPLOYEE (EMPLOYEE_ID,NIC,FIRST_NAME,LAST_NAME,POSITION,EMAIL,PASSWORD,QUESTION,ANSWER,FINGERPRINT) values (2,'23456789','Mohamed Aziz','Darnaoui','Municipal Oversight','azizda@email.tn',null,null,null,null);
Insert into ZIGOOCARE.EMPLOYEE (EMPLOYEE_ID,NIC,FIRST_NAME,LAST_NAME,POSITION,EMAIL,PASSWORD,QUESTION,ANSWER,FINGERPRINT) values (3,'85172155','Maissa','Hammami','Ministry Agent','maissah@email.tn',null,null,null,null);
Insert into ZIGOOCARE.EMPLOYEE (EMPLOYEE_ID,NIC,FIRST_NAME,LAST_NAME,POSITION,EMAIL,PASSWORD,QUESTION,ANSWER,FINGERPRINT) values (4,'17515625','Zayneb','Hergli','Operations Manager','zaynebh@email.tn',null,null,null,null);
Insert into ZIGOOCARE.EMPLOYEE (EMPLOYEE_ID,NIC,FIRST_NAME,LAST_NAME,POSITION,EMAIL,PASSWORD,QUESTION,ANSWER,FINGERPRINT) values (5,'13518625','Youssef','Bouchehioua','Center Representative','youssefb@email.tn',null,null,null,null);
Insert into ZIGOOCARE.EMPLOYEE (EMPLOYEE_ID,NIC,FIRST_NAME,LAST_NAME,POSITION,EMAIL,PASSWORD,QUESTION,ANSWER,FINGERPRINT) values (6,'00000000','Admin','Admin','System Administrator','admin@email.tn',null,null,null,null);
Insert into ZIGOOCARE.EMPLOYEE (EMPLOYEE_ID,NIC,FIRST_NAME,LAST_NAME,POSITION,EMAIL,PASSWORD,QUESTION,ANSWER,FINGERPRINT) values (7,'22222222','Yasmine','Jazi','Operations Manager','yasjazi@email.tn',null,null,null,null);
Insert into ZIGOOCARE.EMPLOYEE (EMPLOYEE_ID,NIC,FIRST_NAME,LAST_NAME,POSITION,EMAIL,PASSWORD,QUESTION,ANSWER,FINGERPRINT) values (8,'11111111','Meliha','Ben Salem','System Administrator','melihabs@email.tn',null,null,null,null);
REM INSERTING into ZIGOOCARE.COLLECTION_TEAM
SET DEFINE OFF;
Insert into ZIGOOCARE.COLLECTION_TEAM (TEAM_ID,TEAM_SIZE,VEHICLE_PLATE,CONTACT_NUMBER,STATUS,PRICE,AVERAGE_RATING,RATING_COUNT,ACTIVE_ASSIGNMENT,AVERAGE_COMPLETION_TIME) values (1,6,'150 TUN 1235','50864769','Available',200,null,null,null,null);
Insert into ZIGOOCARE.COLLECTION_TEAM (TEAM_ID,TEAM_SIZE,VEHICLE_PLATE,CONTACT_NUMBER,STATUS,PRICE,AVERAGE_RATING,RATING_COUNT,ACTIVE_ASSIGNMENT,AVERAGE_COMPLETION_TIME) values (2,6,'157 TUN 1234','50265478','Available',150,3,1,null,null);
Insert into ZIGOOCARE.COLLECTION_TEAM (TEAM_ID,TEAM_SIZE,VEHICLE_PLATE,CONTACT_NUMBER,STATUS,PRICE,AVERAGE_RATING,RATING_COUNT,ACTIVE_ASSIGNMENT,AVERAGE_COMPLETION_TIME) values (3,4,'140 TUN 1587','50417891','Unavailable',150,null,null,null,null);
Insert into ZIGOOCARE.COLLECTION_TEAM (TEAM_ID,TEAM_SIZE,VEHICLE_PLATE,CONTACT_NUMBER,STATUS,PRICE,AVERAGE_RATING,RATING_COUNT,ACTIVE_ASSIGNMENT,AVERAGE_COMPLETION_TIME) values (4,5,'170 TUN 1235','50896574','Available',170,3.66666666666666666666666666666666666667,3,null,null);
Insert into ZIGOOCARE.COLLECTION_TEAM (TEAM_ID,TEAM_SIZE,VEHICLE_PLATE,CONTACT_NUMBER,STATUS,PRICE,AVERAGE_RATING,RATING_COUNT,ACTIVE_ASSIGNMENT,AVERAGE_COMPLETION_TIME) values (0,0,'0','0','0',0,0,0,0,0);
Insert into ZIGOOCARE.COLLECTION_TEAM (TEAM_ID,TEAM_SIZE,VEHICLE_PLATE,CONTACT_NUMBER,STATUS,PRICE,AVERAGE_RATING,RATING_COUNT,ACTIVE_ASSIGNMENT,AVERAGE_COMPLETION_TIME) values (5,2,'140 TUN 778','50145987','Available',140,5,1,null,null);
Insert into ZIGOOCARE.COLLECTION_TEAM (TEAM_ID,TEAM_SIZE,VEHICLE_PLATE,CONTACT_NUMBER,STATUS,PRICE,AVERAGE_RATING,RATING_COUNT,ACTIVE_ASSIGNMENT,AVERAGE_COMPLETION_TIME) values (24,3,'145 TUN 1234','50213654','Available',170,4,1,null,null);
--------------------------------------------------------
--  DDL for Index SEWER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZIGOOCARE"."SEWER_PK" ON "ZIGOOCARE"."SEWER" ("SEWER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MUNICIPALITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZIGOOCARE"."MUNICIPALITY_PK" ON "ZIGOOCARE"."MUNICIPALITY" ("MUNICIPALITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECYCLING_CENTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZIGOOCARE"."RECYCLING_CENTER_PK" ON "ZIGOOCARE"."RECYCLING_CENTER" ("CENTER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INTERVENES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZIGOOCARE"."INTERVENES_PK" ON "ZIGOOCARE"."INTERVENES" ("TEAM_ID", "SEWER_ID", "INTERVENTION_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZIGOOCARE"."EMPLOYEE_PK" ON "ZIGOOCARE"."EMPLOYEE" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COLLECTION_TEAM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZIGOOCARE"."COLLECTION_TEAM_PK" ON "ZIGOOCARE"."COLLECTION_TEAM" ("TEAM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger SEWER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ZIGOOCARE"."SEWER_TRG" 
BEFORE INSERT ON SEWER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SEWER_ID IS NULL THEN
      SELECT SEWER_SEQ.NEXTVAL INTO :NEW.SEWER_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "ZIGOOCARE"."SEWER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MUNICIPALITY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ZIGOOCARE"."MUNICIPALITY_TRG" 
BEFORE INSERT ON MUNICIPALITY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.MUNICIPALITY_ID IS NULL THEN
      SELECT MUNICIPALITY_SEQ.NEXTVAL INTO :NEW.MUNICIPALITY_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "ZIGOOCARE"."MUNICIPALITY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RECYCLING_CENTER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ZIGOOCARE"."RECYCLING_CENTER_TRG" 
BEFORE INSERT ON RECYCLING_CENTER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CENTER_ID IS NULL THEN
      SELECT RECYCLING_CENTER_SEQ.NEXTVAL INTO :NEW.CENTER_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "ZIGOOCARE"."RECYCLING_CENTER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYEE_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ZIGOOCARE"."EMPLOYEE_TRG1" 
BEFORE INSERT ON EMPLOYEE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ZIGOOCARE"."EMPLOYEE_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYEE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ZIGOOCARE"."EMPLOYEE_TRG" 
BEFORE INSERT ON EMPLOYEE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ZIGOOCARE"."EMPLOYEE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYEE_TRG2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ZIGOOCARE"."EMPLOYEE_TRG2" 
BEFORE INSERT ON EMPLOYEE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.EMPLOYEE_ID IS NULL THEN
      SELECT EMPLOYEE_SEQ2.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ZIGOOCARE"."EMPLOYEE_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COLLECTION_TEAM_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ZIGOOCARE"."COLLECTION_TEAM_TRG" 
BEFORE INSERT ON COLLECTION_TEAM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ZIGOOCARE"."COLLECTION_TEAM_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COLLECTION_TEAM_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ZIGOOCARE"."COLLECTION_TEAM_TRG1" 
BEFORE INSERT ON COLLECTION_TEAM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.TEAM_ID IS NULL THEN
      SELECT COLLECTION_TEAM_SEQ1.NEXTVAL INTO :NEW.TEAM_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ZIGOOCARE"."COLLECTION_TEAM_TRG1" ENABLE;
--------------------------------------------------------
--  Constraints for Table SEWER
--------------------------------------------------------

  ALTER TABLE "ZIGOOCARE"."SEWER" MODIFY ("SEWER_ID" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."SEWER" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."SEWER" MODIFY ("MAX_CAPACITY" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."SEWER" MODIFY ("WATER_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."SEWER" ADD CONSTRAINT "SEWER_PK" PRIMARY KEY ("SEWER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MUNICIPALITY
--------------------------------------------------------

  ALTER TABLE "ZIGOOCARE"."MUNICIPALITY" MODIFY ("MUNICIPALITY_ID" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."MUNICIPALITY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."MUNICIPALITY" MODIFY ("REGION" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."MUNICIPALITY" MODIFY ("LONGITUDE" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."MUNICIPALITY" MODIFY ("LATITUDE" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."MUNICIPALITY" MODIFY ("RADIUS" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."MUNICIPALITY" ADD CONSTRAINT "MUNICIPALITY_PK" PRIMARY KEY ("MUNICIPALITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RECYCLING_CENTER
--------------------------------------------------------

  ALTER TABLE "ZIGOOCARE"."RECYCLING_CENTER" MODIFY ("CENTER_ID" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."RECYCLING_CENTER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."RECYCLING_CENTER" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."RECYCLING_CENTER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."RECYCLING_CENTER" MODIFY ("MAX_CAPACITY" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."RECYCLING_CENTER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."RECYCLING_CENTER" ADD CONSTRAINT "RECYCLING_CENTER_PK" PRIMARY KEY ("CENTER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INTERVENES
--------------------------------------------------------

  ALTER TABLE "ZIGOOCARE"."INTERVENES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."INTERVENES" MODIFY ("SEWER_ID" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."INTERVENES" MODIFY ("INTERVENTION_DATE" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."INTERVENES" ADD CONSTRAINT "INTERVENES_PK" PRIMARY KEY ("TEAM_ID", "SEWER_ID", "INTERVENTION_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "ZIGOOCARE"."EMPLOYEE" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."EMPLOYEE" MODIFY ("NIC" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."EMPLOYEE" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."EMPLOYEE" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."EMPLOYEE" MODIFY ("POSITION" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."EMPLOYEE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COLLECTION_TEAM
--------------------------------------------------------

  ALTER TABLE "ZIGOOCARE"."COLLECTION_TEAM" MODIFY ("TEAM_ID" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."COLLECTION_TEAM" MODIFY ("TEAM_SIZE" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."COLLECTION_TEAM" MODIFY ("VEHICLE_PLATE" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."COLLECTION_TEAM" MODIFY ("CONTACT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."COLLECTION_TEAM" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."COLLECTION_TEAM" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "ZIGOOCARE"."COLLECTION_TEAM" ADD CONSTRAINT "COLLECTION_TEAM_PK" PRIMARY KEY ("TEAM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEWER
--------------------------------------------------------

  ALTER TABLE "ZIGOOCARE"."SEWER" ADD CONSTRAINT "SEWER_FK1" FOREIGN KEY ("MUNICIPALITY_ID")
	  REFERENCES "ZIGOOCARE"."MUNICIPALITY" ("MUNICIPALITY_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECYCLING_CENTER
--------------------------------------------------------

  ALTER TABLE "ZIGOOCARE"."RECYCLING_CENTER" ADD CONSTRAINT "RECYCLING_CENTER_FK1" FOREIGN KEY ("MUNICIPALITY_ID")
	  REFERENCES "ZIGOOCARE"."MUNICIPALITY" ("MUNICIPALITY_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INTERVENES
--------------------------------------------------------

  ALTER TABLE "ZIGOOCARE"."INTERVENES" ADD CONSTRAINT "INTERVENES_FK1" FOREIGN KEY ("SEWER_ID")
	  REFERENCES "ZIGOOCARE"."SEWER" ("SEWER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ZIGOOCARE"."INTERVENES" ADD CONSTRAINT "INTERVENES_FK2" FOREIGN KEY ("TEAM_ID")
	  REFERENCES "ZIGOOCARE"."COLLECTION_TEAM" ("TEAM_ID") ON DELETE CASCADE ENABLE;
